### ISSUE TITLE
Pluralsight course - Designing Build Automation

### ISSUE THREAD

**Issue by eliassal** [FeynmanFan/DNOurWebApp#3]
Hi, I watched your session MS Devops solution: Designing Build Automation, in 1st session at minute 15. you show a file called test-build.yaml for DNOurWebApp, I cloned this repo, there is no such file, nor a test project used in the 2nd step.
Can you please let me know how I can get the right source code to play with.
Note: My pluralsight expired yesterday so I can't get any file from there
Thanks in advance

**Comment by FeynmanFan** [comment]
This repo was actually for an earlier course - all of the content that is missing is in an Azure DevOps repo instead of GitHub. I figured the easiest way to get it to you was to just add it here, so I did under the folder "ado-content". Hope that solves your problem.

**Comment by eliassal** [comment]
So many thanks for your efforts and help, I really enjoyed your different sessions

**Comment by eliassal** [comment]
Chris, I followed your instructions until minute 16:52, installed Whitehouse Bolt on my Azure Sevops server 2020, but when I type /choose whitesource bolt  I get a blade hugly different from yours 

![whiteSource](https://user-images.githubusercontent.com/8447864/117532369-85add400-afe7-11eb-8f4b-41e4c34b0b39.jpg)
![whiteSource_002](https://user-images.githubusercontent.com/8447864/117532372-8a728800-afe7-11eb-8560-6129b267dae4.jpg)

adding the 2 lines as you do
```
task: WhiteSource@20
  displayName: 'whitesource Scan'

```
did not help and build fails

![whiteSource_fail](https://user-images.githubusercontent.com/8447864/117532431-c4dc2500-afe7-11eb-8dbc-266a0cc1a0b2.jpg)

Under Pipelines, I don't have A blade for WhiteSourcePipeline where I can enter work email, company, country.......and follow the procedure
![whiteSource_NoBlaid](https://user-images.githubusercontent.com/8447864/117532577-8abf5300-afe8-11eb-9746-0c81c8685c0a.jpg)

**Comment by FeynmanFan** [comment]
It took some digging around, but I think you have installed [this ](https://marketplace.visualstudio.com/items?itemName=anton-kuryan.WhiteSourceScanner) plug-in, instead of [this](https://marketplace.visualstudio.com/items?itemName=whitesource.whiteSource-bolt-v2) one that the course uses. I was able to recreate your screen with that other plug-in.

**Comment by eliassal** [comment]
It seems that the version you use is not available for Azure Devops Server 2020 on-premise

**Comment by FeynmanFan** [comment]
Yeah, the course covers the cloud offering. My best guess from that error message, "Endpoint is null", is that for the on-prem version, you need to set up a Service Connection to Whitesource. You get to Service Connections by going to Project Settings, Service Connections, and creating a new one. Give that a shot and see if you don't have an option to configure one for Whitesource.

**Comment by eliassal** [comment]
I tried but it seems that it is a little bit complex to get a Key. Anyway, I understood the idea and went to next step for Quality checks. 1st Build failed because of unit test failure, digging into the code, it was French/US date format (I am based out of Paris and my box has French regional format). I needed to update the dates into French format as follows in DateManager

 ```
public static DateTime AmericanIndependenceDay = DateTime.Parse("07/04/1776");
 public static DateTime TitanicSank = DateTime.Parse("15/04/1912");
 public static DateTime BattleOfHastings = DateTime.Parse("14/10/1066");
```

As well as the figures to compare in the unit tests (I don't understand why it is different than yours as they are the same dates but in French)
```
public void VerifyDatesSince()
        {
            Assert.AreEqual(38677, DateManager.DaysSince(DateManager.TitanicSank, DateTime.Parse("07/03/2018")));
            Assert.AreEqual(88357, DateManager.DaysSince(DateManager.AmericanIndependenceDay, DateTime.Parse("07/03/2018")));
            Assert.AreEqual(347490, DateManager.DaysSince(DateManager.BattleOfHastings, DateTime.Parse("07/03/2018")));
        }

```

**Comment by eliassal** [comment]
I guess I know why now, it is because my box understands 7th of March and not 3rd of July :-)

**Comment by FeynmanFan** [comment]
Ouch! Local date formats have gotten me way more than once.

**Comment by eliassal** [comment]
Chris, for the 2nd part in build Automation, at minute 7:26 you display right away a Release pipeline but I cant find the details on how to construct this release pipeline, can you share it please? Thanks in advance

**Comment by eliassal** [comment]
Chris, any feedback on this please?

**Comment by FeynmanFan** [comment]
It's found under the Releases item on the right under Pipelines. You can create a release there.

**Comment by eliassal** [comment]
I know where the releases blade is but I am asking if you can provide the yaml or txt for the release pipeline you use in the video, sorry for not being clear

**Comment by FeynmanFan** [comment]
I think this is what you're looking for - you will probably have to make some modifications to it to get it to work...it might be easier to reproduce it in the interface.
[Simple Release Pipeline.zip](https://github.com/FeynmanFan/DNOurWebApp/files/6511736/Simple.Release.Pipeline.zip)
